name: CI/CD for GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate HTML
        run: |
          curl -H "Content-Type: text/html; charset=utf-8" \
               --data-binary @index.html \
               https://validator.w3.org/nu/?out=json > validation.json
          if jq -e '.messages | length > 0' validation.json; then
            echo "HTML validation errors found:"
            jq '.messages[] | {type, message, extract}' validation.json
            exit 1
          else
            echo "HTML validation passed"
          fi

      - name: Minify HTML
        run: |
          sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' -e '/^$/d' \
              -e 's/>[[:space:]]*</></g' index.html > index.min.html
          mv index.min.html index.html
          echo "HTML minified"

      - name: Deploy to GitHub Pages
        if: github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
